[package]
authors=["Ananth Raghav"]
name = "keygen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.1", features = ["derive"] }
copypasta = "0.8.2"
dotenv = "0.15.0"
rand = "0.8.5"